### PR TITLE
Add a globe-3d-terrain-hillshade-hybrid-sat style

### PR DESCRIPTION
**Pull request by birkskyum**
This globe style combines:
- demotiles raster-dem for 3d terrain + hillshade (https://demotiles.maplibre.org/terrain-tiles/tiles.json)
- stadia maps alidade hybrid satellite style (https://docs.stadiamaps.com/map-styles/alidade-satellite)

Related to:
- https://github.com/maplibre/maplibre-gl-js/pull/4926

Screenshot 2024-10-29 at 16 56 32

### CODE REVIEW

**Comment by HarelM** [comment]
Do we have licensing issue since part of the style is based on maptiler?

**Comment by birkskyum** [comment]
I don't think it's a problem.

**Comment by HarelM** [comment]
Less about billing, more about creative type of license...? Copy modify issues? 
There's a lot of attributions here: 
https://www.maptiler.com/copyright/

**Comment by birkskyum** [comment]
@HarelM these are the rendered attributions, using the stadia maps alidade sat hybrid - there's already a maptiler sat example (satellite-map.html) , so i figured it could give some variety
Screenshot 2024-10-29 at 18 33 38


cc @lseelenbinder , would it be a license issue for maplibre to copy the alidade sat style.json, modified by applying [these changes](https://github.com/maplibre/maplibre-gl-js/pull/4926/files#diff-b88b9f6ee362d7e913378291de314059e3581b7942f75d3296ed4582f4e9e29aR40-R69), into the demotiles repo here? It's just for convenience of having an example to debug (and potentially a website showcase) of photo-realistic rendering, without these 30L of style transform.

**Comment by lseelenbinder** [comment]
Yes, that's fine @birkskyum! Missed this alert earlier.

**Pull request closed without merging**
