### PR TITLE
Add OpenMapTiles demotiles for more complex testing

### PR DESCRIPTION
**Pull request by acalcutt**
This is an attempt make more complex demo tiles for https://github.com/maplibre/maplibre-gl-js/issues/198

I have created omt tiles of the N047E011 region using planetiler, extracted them with mbutil, uncompressed the pbf files, and put them into the 'tiles-omt' directory. I have also added osm bright based styles and added the fonts this style requires. I added in spites which I created for my own project which are a based on open sources and a little more complex than the ones that come with osm bright.

I have created a test here
https://github.com/WifiDB/demotiles/tree/gh-pages/

I have created two demo pages here
https://wifidb.github.io/demotiles/tiles-omt/ (new omt demo tile with a osm-bright-gl style)
https://wifidb.github.io/demotiles/terrain-tiles/ (same with terrain and hillshade added)

Here are some screenshots in use
image
image

### CODE REVIEW

**Review by HarelM — APPROVED** [review]
Obviously this can't be reviewed as it has too many files... :-)

**Comment by HarelM** [comment]
Are all the things added here "copyright" free?

**Comment by acalcutt** [comment]
I tried to keep or add license information where it was required.

The tiles I generated myself and they contain the proper OpenMapTiles/OpenStreetMap attributions.

The sprites I generated myself with https://github.com/acalcutt/icon-fonts . As far as I can tell the licenses for the svgs used are open, you can see where they all came from and their licenses here ( https://github.com/acalcutt/icon-fonts/tree/master/svg/furkot )

The fonts came from https://github.com/openmaptiles/fonts

The style is https://github.com/openmaptiles/osm-bright-gl-style with some modifications.

**Comment by acalcutt** [comment]
Looks like the Noto fonts are OFL License

The style is BSD 3-Clause License with CC-BY 4.0. The attribution for OpenMapTiles is included in the tiles and the license in included with the style.

I guess the sprites could be simplified to the ones that come with [osm-bright-gl-style](https://github.com/openmaptiles/osm-bright-gl-style), since that could make licensing easier.

**Comment by acalcutt** [comment]
I changed the sprites to use the ones included with [osm-bright-gl-style](https://github.com/openmaptiles/osm-bright-gl-style) and moved them to inside the style folders so they could be covered by the same openmaptiles LICENSE.md file.  These are a lot more basic, but at least they have a more clear license.

**Comment by acalcutt** [comment]
Also, I know this is hard to review because of the amount of files, but that can't really be helped because of the tiles and fonts added.

If you look at https://github.com/wifidb/demotiles/tree/ml_tiles

What I have added is the following

** Fonts used by the osm-bright style **
font\Noto Sans Bold
font\Noto Sans Italic
font\Noto Sans Regular
(768 Files / 99.7MB)

** Styles based on osm bright **
styles\osm-bright-gl-style
styles\osm-bright-gl-terrain

** OMT vector tile pbf files in the N047E011 region **
tiles-omt\\(0-14) 
(4,377 files / 87.9MB)

** Tilejson Generated by tileserver-gl **
tiles-omt\tiles.json

** Demo Pages **
tiles-omt\index.html
terrain-tiles\index.html

** READMES **
tiles-omt\README.md
styles\osm-bright-gl-style\README.md
styles\osm-bright-gl-terrain\README.md

I thought about moving the root directory style.json into the styles folder, but I didn't want to change what was already in place. might be something to do in a future PR though. 

Let me know if there are any other concerns or recommendations.

**Comment by HarelM** [comment]
Besides licenses and clone time, I can't think of other things...

**Comment by acalcutt** [comment]
I think the license should be fine now, no?

 I offer the tiles i generated without a license beyond the attributions required. the attributions are included.

the font and styles both have a permsissive open license that i included inside the directories. the font OFL license allows modification and redistibution ([see here](https://github.com/maplibre/demotiles/pull/12/commits/63ea2f9a42cd56ec3c3fc213c1c40ad2ae119c17)). the style allows redistribution with attribution, which I have [here](https://github.com/WifiDB/demotiles/blob/ml_tiles/styles/osm-bright-gl-style/LICENSE.md). 

I also think the checkout will end up faster than it is on my fork because I have a few branches with a lot more tiles that this won't have (checkout on my fork checks out 50,000 files, but this only adds about 5,000)

**Comment by HarelM** [comment]
Ok, let's merge, we can always revert.

**Comment by acalcutt** [comment]
Nice, it looks like it is working at these urls :-)

https://demotiles.maplibre.org/tiles-omt/
https://demotiles.maplibre.org/terrain-tiles/

**Comment by acalcutt** [comment]
looks like it took me about 30 seconds to checkout the repo, so it doesn't seem much slower than before...awesome.

**Pull request merged**
